version: '3.9'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SuaSenhaForte_123
    ports:
      - '1433:1433'
    volumes:
      - ./mssql_data:/var/opt/mssql
